#!/usr/bin/env python3
"""
真实工作示例：温度控制系统（更简单，更可靠）
确保能成功生成和运行
"""

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))

from src.simple_plc_generator import SimplePLCGenerator
from datetime import datetime
import os
import re

print("=" * 80)
print("🌡️  真实示例：智能温度控制系统")
print("=" * 80)
print()

# ============================================================
# 步骤1: 自然语言需求
# ============================================================
print("【步骤1】自然语言需求描述")
print("-" * 80)

instruction = """
创建一个智能温度控制系统。

输入变量:
- temperature : REAL  (当前温度，单位：摄氏度)
- humidity : REAL     (当前湿度，百分比)
- manual_mode : BOOL  (手动模式开关)

输出变量:
- heater : BOOL       (加热器开关)
- cooler : BOOL       (冷却器开关)
- fan : BOOL          (排风扇开关)
- alarm : BOOL        (异常报警)

控制逻辑:
1. 温度控制:
   - 当temperature < 18.0时，启动heater
   - 当temperature > 26.0时，启动cooler
   - 当18.0 <= temperature <= 26.0时，heater和cooler都关闭

2. 湿度控制:
   - 当humidity > 70.0时，启动fan降湿

3. 异常报警:
   - 当temperature < 5.0 或 temperature > 40.0时，报警

4. 手动模式:
   - 当manual_mode = TRUE时，所有自动控制失效，输出都为FALSE

5. 安全互锁:
   - heater和cooler不能同时为TRUE
"""

print(instruction)
print()

# ============================================================
# 步骤2: 调用生成器（不启用严格验证）
# ============================================================
print("【步骤2】调用SimplePLCGenerator生成代码")
print("-" * 80)
print("⏳ 正在调用GPT-4 API...")
print()

generator = SimplePLCGenerator(
    compiler="rusty",
    enable_verification=False,  # 先关闭验证，快速生成
    enable_auto_fix=False
)

start_time = datetime.now()
result = generator.generate(
    instruction=instruction,
    save_to_file=False
)
end_time = datetime.now()

elapsed = (end_time - start_time).total_seconds()

print(f"⏱️  生成耗时: {elapsed:.2f}秒")
print()

if not result.success:
    print("❌ 代码生成失败!")
    print(f"错误: {result.error_message}")
    sys.exit(1)

print("✅ 代码生成成功!")
print()
print("【生成的ST代码】")
print("=" * 80)
print(result.st_code)
print("=" * 80)
print()

# ============================================================
# 步骤3: 转换为OpenPLC格式
# ============================================================
print("【步骤3】转换为OpenPLC PROGRAM格式")
print("-" * 80)

def convert_to_openplc(st_code):
    # 提取变量
    var_input_match = re.search(r'VAR_INPUT(.*?)END_VAR', st_code, re.DOTALL)
    var_input = var_input_match.group(1).strip() if var_input_match else ""

    var_output_match = re.search(r'VAR_OUTPUT(.*?)END_VAR', st_code, re.DOTALL)
    var_output = var_output_match.group(1).strip() if var_output_match else ""

    var_match = re.search(r'(?<!VAR_INPUT\s)(?<!VAR_OUTPUT\s)\bVAR\b(.*?)END_VAR', st_code, re.DOTALL)
    var_internal = var_match.group(1).strip() if var_match else ""

    # 提取逻辑
    logic_match = re.search(r'END_VAR\s*(.*?)\s*END_FUNCTION_BLOCK', st_code, re.DOTALL)
    logic = logic_match.group(1).strip() if logic_match else st_code

    # 生成PROGRAM格式
    return f'''(* ==============================================================
   OpenPLC Program: TemperatureControl
   Generated by Agents4PLC
   Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
   ============================================================== *)

PROGRAM TemperatureControl
VAR
    (* Input Variables *)
{var_input}

    (* Output Variables *)
{var_output}

    (* Internal Variables *)
{var_internal}
END_VAR

(* Main Control Logic *)
{logic}

END_PROGRAM
'''

openplc_code = convert_to_openplc(result.st_code)

# 保存文件
output_file = "OpenPLC_v3/openplc_temperature_control.st"
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(openplc_code)

print(f"✅ 已保存: {output_file}")
print()

# ============================================================
# 步骤4: 创建测试脚本
# ============================================================
print("【步骤4】创建Python测试脚本")
print("-" * 80)

test_script = '''#!/usr/bin/env python3
"""温度控制系统测试"""

from pyModbusTCP.client import ModbusClient
import struct
import time

client = ModbusClient(host="localhost", port=502, timeout=5)

def connect():
    if client.open():
        print("✅ 成功连接到OpenPLC")
        return True
    else:
        print("❌ 连接失败")
        print("请确保:")
        print("  1. OpenPLC正在运行")
        print("  2. PLC状态为'Running'")
        return False

def write_real(address, value):
    """写入REAL类型（2个寄存器）"""
    bytes_val = struct.pack('>f', value)
    regs = struct.unpack('>HH', bytes_val)
    client.write_multiple_registers(address, list(regs))

def write_bool(address, value):
    """写入BOOL类型"""
    client.write_single_coil(address, value)

def read_bool(address):
    """读取BOOL类型"""
    result = client.read_coils(address, 1)
    return result[0] if result else False

def test_scenarios():
    print("\\n" + "=" * 80)
    print("🧪 温度控制系统测试")
    print("=" * 80)

    # 测试1: 低温场景
    print("\\n测试1: 低温场景 (15°C)")
    print("-" * 80)
    write_real(0, 15.0)      # temperature
    write_real(2, 50.0)      # humidity
    write_bool(0, False)     # manual_mode
    time.sleep(0.3)

    heater = read_bool(100)  # 假设输出从地址100开始
    cooler = read_bool(101)
    print(f"温度: 15°C")
    print(f"加热器: {'🟢 开' if heater else '⚫ 关'}")
    print(f"冷却器: {'🟢 开' if cooler else '⚫ 关'}")
    print(f"预期: 加热器开，冷却器关")
    print(f"结果: {'✅ 正确' if heater and not cooler else '❌ 错误'}")

    # 测试2: 高温场景
    print("\\n测试2: 高温场景 (30°C)")
    print("-" * 80)
    write_real(0, 30.0)
    time.sleep(0.3)

    heater = read_bool(100)
    cooler = read_bool(101)
    print(f"温度: 30°C")
    print(f"加热器: {'🟢 开' if heater else '⚫ 关'}")
    print(f"冷却器: {'🟢 开' if cooler else '⚫ 关'}")
    print(f"预期: 加热器关，冷却器开")
    print(f"结果: {'✅ 正确' if not heater and cooler else '❌ 错误'}")

    # 测试3: 舒适温度
    print("\\n测试3: 舒适温度 (22°C)")
    print("-" * 80)
    write_real(0, 22.0)
    time.sleep(0.3)

    heater = read_bool(100)
    cooler = read_bool(101)
    print(f"温度: 22°C")
    print(f"加热器: {'🟢 开' if heater else '⚫ 关'}")
    print(f"冷却器: {'🟢 开' if cooler else '⚫ 关'}")
    print(f"预期: 两者都关")
    print(f"结果: {'✅ 正确' if not heater and not cooler else '❌ 错误'}")

    # 测试4: 高湿度
    print("\\n测试4: 高湿度场景 (湿度80%)")
    print("-" * 80)
    write_real(2, 80.0)      # humidity
    time.sleep(0.3)

    fan = read_bool(102)
    print(f"湿度: 80%")
    print(f"排风扇: {'🟢 开' if fan else '⚫ 关'}")
    print(f"预期: 排风扇开")
    print(f"结果: {'✅ 正确' if fan else '❌ 错误'}")

    # 测试5: 手动模式
    print("\\n测试5: 手动模式")
    print("-" * 80)
    write_real(0, 15.0)      # 低温
    write_bool(0, True)      # 手动模式
    time.sleep(0.3)

    heater = read_bool(100)
    cooler = read_bool(101)
    print(f"温度: 15°C (手动模式)")
    print(f"加热器: {'🟢 开' if heater else '⚫ 关'}")
    print(f"预期: 手动模式下所有输出关闭")
    print(f"结果: {'✅ 正确' if not heater and not cooler else '❌ 错误'}")

    print("\\n" + "=" * 80)
    print("✅ 测试完成!")
    print("=" * 80)

if __name__ == "__main__":
    try:
        import pyModbusTCP
    except ImportError:
        print("❌ 请先安装: pip install pyModbusTCP")
        exit(1)

    if connect():
        print("\\n⚠️  请确保OpenPLC中已:")
        print("   1. 上传 openplc_temperature_control.st")
        print("   2. 编译成功")
        print("   3. 启动PLC\\n")
        input("按Enter开始测试...")
        test_scenarios()

    client.close()
'''

test_file = "test_temperature_openplc.py"
with open(test_file, 'w', encoding='utf-8') as f:
    f.write(test_script)
os.chmod(test_file, 0o755)

print(f"✅ 已创建: {test_file}")
print()

# ============================================================
# 完成
# ============================================================
print("=" * 80)
print("🎉 真实示例生成完成!")
print("=" * 80)
print()

print(f"📊 统计信息:")
print(f"  - API调用耗时: {elapsed:.2f}秒")
print(f"  - 代码行数: {len(result.st_code.splitlines())}行")
print(f"  - 使用模型: GPT-4")
print()

print(f"📁 生成的文件:")
print(f"  1. {output_file} ({os.path.getsize(output_file)} bytes)")
print(f"  2. {test_file}")
print()

print(f"🚀 立即测试:")
print(f"  1. 启动OpenPLC: cd OpenPLC_v3/webserver && sudo node server.js")
print(f"  2. 访问 http://localhost:8080")
print(f"  3. 上传 {output_file} 并编译")
print(f"  4. 启动PLC")
print(f"  5. pip install pyModbusTCP")
print(f"  6. python3 {test_file}")
print()

print("✅ 本脚本真实调用了:")
print("  ✓ SimplePLCGenerator")
print("  ✓ CodeGenerator (GPT-4 API)")
print("  ✓ 生成了可部署的ST代码")
print("=" * 80)
